var QRCode;
!function(){function a(e){this.mode=l.MODE_8BIT_BYTE;this.data=e;this.parsedData=[];e=[];for(var g=0,h=this.data.length;h>g;g++){var f=this.data.charCodeAt(g);65536<f?(e[0]=240|(1835008&f)>>>18,e[1]=128|(258048&f)>>>12,e[2]=128|(4032&f)>>>6,e[3]=128|63&f):2048<f?(e[0]=224|(61440&f)>>>12,e[1]=128|(4032&f)>>>6,e[2]=128|63&f):128<f?(e[0]=192|(1984&f)>>>6,e[1]=128|63&f):e[0]=f;this.parsedData=this.parsedData.concat(e)}this.parsedData.length!=this.data.length&&(this.parsedData.unshift(191),this.parsedData.unshift(187),
this.parsedData.unshift(239))}function c(e,g){this.typeNumber=e;this.errorCorrectLevel=g;this.modules=null;this.moduleCount=0;this.dataCache=null;this.dataList=[]}function b(e,g){if(void 0==e.length)throw Error(e.length+"/"+g);for(var h=0;h<e.length&&0==e[h];)h++;this.num=Array(e.length-h+g);for(var f=0;f<e.length-h;f++)this.num[f]=e[f+h]}function d(e,g){this.totalCount=e;this.dataCount=g}function k(){this.buffer=[];this.length=0}function n(){var e=!1,g=navigator.userAgent;return/android/i.test(g)&&
(e=!0,aMat=g.toString().match(/android ([0-9]\.[0-9])/i),aMat&&aMat[1]&&(e=parseFloat(aMat[1]))),e}a.prototype={getLength:function(){return this.parsedData.length},write:function(e){for(var g=0,h=this.parsedData.length;h>g;g++)e.put(this.parsedData[g],8)}};c.prototype={addData:function(e){e=new a(e);this.dataList.push(e);this.dataCache=null},isDark:function(e,g){if(0>e||this.moduleCount<=e||0>g||this.moduleCount<=g)throw Error(e+","+g);return this.modules[e][g]},getModuleCount:function(){return this.moduleCount},
make:function(){this.makeImpl(!1,this.getBestMaskPattern())},makeImpl:function(e,g){this.moduleCount=4*this.typeNumber+17;this.modules=Array(this.moduleCount);for(var h=0;h<this.moduleCount;h++){this.modules[h]=Array(this.moduleCount);for(var f=0;f<this.moduleCount;f++)this.modules[h][f]=null}this.setupPositionProbePattern(0,0);this.setupPositionProbePattern(this.moduleCount-7,0);this.setupPositionProbePattern(0,this.moduleCount-7);this.setupPositionAdjustPattern();this.setupTimingPattern();this.setupTypeInfo(e,
g);7<=this.typeNumber&&this.setupTypeNumber(e);null==this.dataCache&&(this.dataCache=c.createData(this.typeNumber,this.errorCorrectLevel,this.dataList));this.mapData(this.dataCache,g)},setupPositionProbePattern:function(e,g){for(var h=-1;7>=h;h++)if(!(-1>=e+h||this.moduleCount<=e+h))for(var f=-1;7>=f;f++)-1>=g+f||this.moduleCount<=g+f||(this.modules[e+h][g+f]=0<=h&&6>=h&&(0==f||6==f)||0<=f&&6>=f&&(0==h||6==h)||2<=h&&4>=h&&2<=f&&4>=f?!0:!1)},getBestMaskPattern:function(){for(var e=0,g=0,h=0;8>h;h++){this.makeImpl(!0,
h);var f=q.getLostPoint(this);(0==h||e>f)&&(e=f,g=h)}return g},createMovieClip:function(e,g,h){e=e.createEmptyMovieClip(g,h);this.make();for(g=0;g<this.modules.length;g++){h=1*g;for(var f=0;f<this.modules[g].length;f++){var m=1*f;this.modules[g][f]&&(e.beginFill(0,100),e.moveTo(m,h),e.lineTo(m+1,h),e.lineTo(m+1,h+1),e.lineTo(m,h+1),e.endFill())}}return e},setupTimingPattern:function(){for(var e=8;e<this.moduleCount-8;e++)null==this.modules[e][6]&&(this.modules[e][6]=0==e%2);for(e=8;e<this.moduleCount-
8;e++)null==this.modules[6][e]&&(this.modules[6][e]=0==e%2)},setupPositionAdjustPattern:function(){for(var e=q.getPatternPosition(this.typeNumber),g=0;g<e.length;g++)for(var h=0;h<e.length;h++){var f=e[g],m=e[h];if(null==this.modules[f][m])for(var u=-2;2>=u;u++)for(var w=-2;2>=w;w++)this.modules[f+u][m+w]=-2==u||2==u||-2==w||2==w||0==u&&0==w?!0:!1}},setupTypeNumber:function(e){for(var g=q.getBCHTypeNumber(this.typeNumber),h=0;18>h;h++){var f=!e&&1==(1&g>>h);this.modules[Math.floor(h/3)][h%3+this.moduleCount-
8-3]=f}for(h=0;18>h;h++)f=!e&&1==(1&g>>h),this.modules[h%3+this.moduleCount-8-3][Math.floor(h/3)]=f},setupTypeInfo:function(e,g){for(var h=q.getBCHTypeInfo(this.errorCorrectLevel<<3|g),f=0;15>f;f++){var m=!e&&1==(1&h>>f);6>f?this.modules[f][8]=m:8>f?this.modules[f+1][8]=m:this.modules[this.moduleCount-15+f][8]=m}for(f=0;15>f;f++)m=!e&&1==(1&h>>f),8>f?this.modules[8][this.moduleCount-f-1]=m:9>f?this.modules[8][15-f-1+1]=m:this.modules[8][15-f-1]=m;this.modules[this.moduleCount-8][8]=!e},mapData:function(e,
g){for(var h=-1,f=this.moduleCount-1,m=7,u=0,w=this.moduleCount-1;0<w;w-=2)for(6==w&&w--;;){for(var t=0;2>t;t++)if(null==this.modules[f][w-t]){var B=!1;u<e.length&&(B=1==(1&e[u]>>>m));q.getMask(g,f,w-t)&&(B=!B);this.modules[f][w-t]=B;m--;-1==m&&(u++,m=7)}if(f+=h,0>f||this.moduleCount<=f){f-=h;h=-h;break}}}};c.PAD0=236;c.PAD1=17;c.createData=function(e,g,h){g=d.getRSBlocks(e,g);for(var f=new k,m=0;m<h.length;m++){var u=h[m];f.put(u.mode,4);f.put(u.getLength(),q.getLengthInBits(u.mode,e));u.write(f)}for(m=
e=0;m<g.length;m++)e+=g[m].dataCount;if(f.getLengthInBits()>8*e)throw Error("code length overflow. ("+f.getLengthInBits()+">"+8*e+")");for(f.getLengthInBits()+4<=8*e&&f.put(0,4);0!=f.getLengthInBits()%8;)f.putBit(!1);for(;!(f.getLengthInBits()>=8*e||(f.put(c.PAD0,8),f.getLengthInBits()>=8*e));)f.put(c.PAD1,8);return c.createBytes(f,g)};c.createBytes=function(e,g){for(var h=0,f=0,m=0,u=Array(g.length),w=Array(g.length),t=0;t<g.length;t++){var B=g[t].dataCount,G=g[t].totalCount-B;f=Math.max(f,B);m=
Math.max(m,G);u[t]=Array(B);for(var C=0;C<u[t].length;C++)u[t][C]=255&e.buffer[C+h];h+=B;C=q.getErrorCorrectPolynomial(G);B=(new b(u[t],C.getLength()-1)).mod(C);w[t]=Array(C.getLength()-1);for(C=0;C<w[t].length;C++)G=C+B.getLength()-w[t].length,w[t][C]=0<=G?B.get(G):0}for(C=t=0;C<g.length;C++)t+=g[C].totalCount;h=Array(t);for(C=B=0;f>C;C++)for(t=0;t<g.length;t++)C<u[t].length&&(h[B++]=u[t][C]);for(C=0;m>C;C++)for(t=0;t<g.length;t++)C<w[t].length&&(h[B++]=w[t][C]);return h};for(var l={MODE_NUMBER:1,
MODE_ALPHA_NUM:2,MODE_8BIT_BYTE:4,MODE_KANJI:8},y={L:1,M:0,Q:3,H:2},q={PATTERN_POSITION_TABLE:[[],[6,18],[6,22],[6,26],[6,30],[6,34],[6,22,38],[6,24,42],[6,26,46],[6,28,50],[6,30,54],[6,32,58],[6,34,62],[6,26,46,66],[6,26,48,70],[6,26,50,74],[6,30,54,78],[6,30,56,82],[6,30,58,86],[6,34,62,90],[6,28,50,72,94],[6,26,50,74,98],[6,30,54,78,102],[6,28,54,80,106],[6,32,58,84,110],[6,30,58,86,114],[6,34,62,90,118],[6,26,50,74,98,122],[6,30,54,78,102,126],[6,26,52,78,104,130],[6,30,56,82,108,134],[6,34,60,
86,112,138],[6,30,58,86,114,142],[6,34,62,90,118,146],[6,30,54,78,102,126,150],[6,24,50,76,102,128,154],[6,28,54,80,106,132,158],[6,32,58,84,110,136,162],[6,26,54,82,110,138,166],[6,30,58,86,114,142,170]],G15:1335,G18:7973,G15_MASK:21522,getBCHTypeInfo:function(e){for(var g=e<<10;0<=q.getBCHDigit(g)-q.getBCHDigit(q.G15);)g^=q.G15<<q.getBCHDigit(g)-q.getBCHDigit(q.G15);return(e<<10|g)^q.G15_MASK},getBCHTypeNumber:function(e){for(var g=e<<12;0<=q.getBCHDigit(g)-q.getBCHDigit(q.G18);)g^=q.G18<<q.getBCHDigit(g)-
q.getBCHDigit(q.G18);return e<<12|g},getBCHDigit:function(e){for(var g=0;0!=e;)g++,e>>>=1;return g},getPatternPosition:function(e){return q.PATTERN_POSITION_TABLE[e-1]},getMask:function(e,g,h){switch(e){case 0:return 0==(g+h)%2;case 1:return 0==g%2;case 2:return 0==h%3;case 3:return 0==(g+h)%3;case 4:return 0==(Math.floor(g/2)+Math.floor(h/3))%2;case 5:return 0==g*h%2+g*h%3;case 6:return 0==(g*h%2+g*h%3)%2;case 7:return 0==(g*h%3+(g+h)%2)%2;default:throw Error("bad maskPattern:"+e);}},getErrorCorrectPolynomial:function(e){for(var g=
new b([1],0),h=0;e>h;h++)g=g.multiply(new b([1,A.gexp(h)],0));return g},getLengthInBits:function(e,g){if(1<=g&&10>g)switch(e){case l.MODE_NUMBER:return 10;case l.MODE_ALPHA_NUM:return 9;case l.MODE_8BIT_BYTE:return 8;case l.MODE_KANJI:return 8;default:throw Error("mode:"+e);}else if(27>g)switch(e){case l.MODE_NUMBER:return 12;case l.MODE_ALPHA_NUM:return 11;case l.MODE_8BIT_BYTE:return 16;case l.MODE_KANJI:return 10;default:throw Error("mode:"+e);}else{if(!(41>g))throw Error("type:"+g);switch(e){case l.MODE_NUMBER:return 14;
case l.MODE_ALPHA_NUM:return 13;case l.MODE_8BIT_BYTE:return 16;case l.MODE_KANJI:return 12;default:throw Error("mode:"+e);}}},getLostPoint:function(e){for(var g=e.getModuleCount(),h=0,f=0;g>f;f++)for(var m=0;g>m;m++){for(var u=0,w=e.isDark(f,m),t=-1;1>=t;t++)if(!(0>f+t||f+t>=g))for(var B=-1;1>=B;B++)0>m+B||m+B>=g||(0!=t||0!=B)&&w==e.isDark(f+t,m+B)&&u++;5<u&&(h+=3+u-5)}for(f=0;g-1>f;f++)for(m=0;g-1>m;m++)u=0,e.isDark(f,m)&&u++,e.isDark(f+1,m)&&u++,e.isDark(f,m+1)&&u++,e.isDark(f+1,m+1)&&u++,0!=u&&
4!=u||(h+=3);for(f=0;g>f;f++)for(m=0;g-6>m;m++)e.isDark(f,m)&&!e.isDark(f,m+1)&&e.isDark(f,m+2)&&e.isDark(f,m+3)&&e.isDark(f,m+4)&&!e.isDark(f,m+5)&&e.isDark(f,m+6)&&(h+=40);for(m=0;g>m;m++)for(f=0;g-6>f;f++)e.isDark(f,m)&&!e.isDark(f+1,m)&&e.isDark(f+2,m)&&e.isDark(f+3,m)&&e.isDark(f+4,m)&&!e.isDark(f+5,m)&&e.isDark(f+6,m)&&(h+=40);for(m=u=0;g>m;m++)for(f=0;g>f;f++)e.isDark(f,m)&&u++;return h+Math.abs(100*u/g/g-50)/5*10}},A={glog:function(e){if(1>e)throw Error("glog("+e+")");return A.LOG_TABLE[e]},
gexp:function(e){for(;0>e;)e+=255;for(;256<=e;)e-=255;return A.EXP_TABLE[e]},EXP_TABLE:Array(256),LOG_TABLE:Array(256)},E=0;8>E;E++)A.EXP_TABLE[E]=1<<E;for(E=8;256>E;E++)A.EXP_TABLE[E]=A.EXP_TABLE[E-4]^A.EXP_TABLE[E-5]^A.EXP_TABLE[E-6]^A.EXP_TABLE[E-8];for(E=0;255>E;E++)A.LOG_TABLE[A.EXP_TABLE[E]]=E;b.prototype={get:function(e){return this.num[e]},getLength:function(){return this.num.length},multiply:function(e){for(var g=Array(this.getLength()+e.getLength()-1),h=0;h<this.getLength();h++)for(var f=
0;f<e.getLength();f++)g[h+f]^=A.gexp(A.glog(this.get(h))+A.glog(e.get(f)));return new b(g,0)},mod:function(e){if(0>this.getLength()-e.getLength())return this;for(var g=A.glog(this.get(0))-A.glog(e.get(0)),h=Array(this.getLength()),f=0;f<this.getLength();f++)h[f]=this.get(f);for(f=0;f<e.getLength();f++)h[f]^=A.gexp(A.glog(e.get(f))+g);return(new b(h,0)).mod(e)}};d.RS_BLOCK_TABLE=[[1,26,19],[1,26,16],[1,26,13],[1,26,9],[1,44,34],[1,44,28],[1,44,22],[1,44,16],[1,70,55],[1,70,44],[2,35,17],[2,35,13],
[1,100,80],[2,50,32],[2,50,24],[4,25,9],[1,134,108],[2,67,43],[2,33,15,2,34,16],[2,33,11,2,34,12],[2,86,68],[4,43,27],[4,43,19],[4,43,15],[2,98,78],[4,49,31],[2,32,14,4,33,15],[4,39,13,1,40,14],[2,121,97],[2,60,38,2,61,39],[4,40,18,2,41,19],[4,40,14,2,41,15],[2,146,116],[3,58,36,2,59,37],[4,36,16,4,37,17],[4,36,12,4,37,13],[2,86,68,2,87,69],[4,69,43,1,70,44],[6,43,19,2,44,20],[6,43,15,2,44,16],[4,101,81],[1,80,50,4,81,51],[4,50,22,4,51,23],[3,36,12,8,37,13],[2,116,92,2,117,93],[6,58,36,2,59,37],[4,
46,20,6,47,21],[7,42,14,4,43,15],[4,133,107],[8,59,37,1,60,38],[8,44,20,4,45,21],[12,33,11,4,34,12],[3,145,115,1,146,116],[4,64,40,5,65,41],[11,36,16,5,37,17],[11,36,12,5,37,13],[5,109,87,1,110,88],[5,65,41,5,66,42],[5,54,24,7,55,25],[11,36,12],[5,122,98,1,123,99],[7,73,45,3,74,46],[15,43,19,2,44,20],[3,45,15,13,46,16],[1,135,107,5,136,108],[10,74,46,1,75,47],[1,50,22,15,51,23],[2,42,14,17,43,15],[5,150,120,1,151,121],[9,69,43,4,70,44],[17,50,22,1,51,23],[2,42,14,19,43,15],[3,141,113,4,142,114],[3,
70,44,11,71,45],[17,47,21,4,48,22],[9,39,13,16,40,14],[3,135,107,5,136,108],[3,67,41,13,68,42],[15,54,24,5,55,25],[15,43,15,10,44,16],[4,144,116,4,145,117],[17,68,42],[17,50,22,6,51,23],[19,46,16,6,47,17],[2,139,111,7,140,112],[17,74,46],[7,54,24,16,55,25],[34,37,13],[4,151,121,5,152,122],[4,75,47,14,76,48],[11,54,24,14,55,25],[16,45,15,14,46,16],[6,147,117,4,148,118],[6,73,45,14,74,46],[11,54,24,16,55,25],[30,46,16,2,47,17],[8,132,106,4,133,107],[8,75,47,13,76,48],[7,54,24,22,55,25],[22,45,15,13,
46,16],[10,142,114,2,143,115],[19,74,46,4,75,47],[28,50,22,6,51,23],[33,46,16,4,47,17],[8,152,122,4,153,123],[22,73,45,3,74,46],[8,53,23,26,54,24],[12,45,15,28,46,16],[3,147,117,10,148,118],[3,73,45,23,74,46],[4,54,24,31,55,25],[11,45,15,31,46,16],[7,146,116,7,147,117],[21,73,45,7,74,46],[1,53,23,37,54,24],[19,45,15,26,46,16],[5,145,115,10,146,116],[19,75,47,10,76,48],[15,54,24,25,55,25],[23,45,15,25,46,16],[13,145,115,3,146,116],[2,74,46,29,75,47],[42,54,24,1,55,25],[23,45,15,28,46,16],[17,145,115],
[10,74,46,23,75,47],[10,54,24,35,55,25],[19,45,15,35,46,16],[17,145,115,1,146,116],[14,74,46,21,75,47],[29,54,24,19,55,25],[11,45,15,46,46,16],[13,145,115,6,146,116],[14,74,46,23,75,47],[44,54,24,7,55,25],[59,46,16,1,47,17],[12,151,121,7,152,122],[12,75,47,26,76,48],[39,54,24,14,55,25],[22,45,15,41,46,16],[6,151,121,14,152,122],[6,75,47,34,76,48],[46,54,24,10,55,25],[2,45,15,64,46,16],[17,152,122,4,153,123],[29,74,46,14,75,47],[49,54,24,10,55,25],[24,45,15,46,46,16],[4,152,122,18,153,123],[13,74,
46,32,75,47],[48,54,24,14,55,25],[42,45,15,32,46,16],[20,147,117,4,148,118],[40,75,47,7,76,48],[43,54,24,22,55,25],[10,45,15,67,46,16],[19,148,118,6,149,119],[18,75,47,31,76,48],[34,54,24,34,55,25],[20,45,15,61,46,16]];d.getRSBlocks=function(e,g){var h=d.getRsBlockTable(e,g);if(void 0==h)throw Error("bad rs block @ typeNumber:"+e+"/errorCorrectLevel:"+g);for(var f=h.length/3,m=[],u=0;f>u;u++)for(var w=h[3*u],t=h[3*u+1],B=h[3*u+2],G=0;w>G;G++)m.push(new d(t,B));return m};d.getRsBlockTable=function(e,
g){switch(g){case y.L:return d.RS_BLOCK_TABLE[4*(e-1)];case y.M:return d.RS_BLOCK_TABLE[4*(e-1)+1];case y.Q:return d.RS_BLOCK_TABLE[4*(e-1)+2];case y.H:return d.RS_BLOCK_TABLE[4*(e-1)+3]}};k.prototype={get:function(e){return 1==(1&this.buffer[Math.floor(e/8)]>>>7-e%8)},put:function(e,g){for(var h=0;g>h;h++)this.putBit(1==(1&e>>>g-h-1))},getLengthInBits:function(){return this.length},putBit:function(e){var g=Math.floor(this.length/8);this.buffer.length<=g&&this.buffer.push(0);e&&(this.buffer[g]|=128>>>
this.length%8);this.length++}};var J=[[17,14,11,7],[32,26,20,14],[53,42,32,24],[78,62,46,34],[106,84,60,44],[134,106,74,58],[154,122,86,64],[192,152,108,84],[230,180,130,98],[271,213,151,119],[321,251,177,137],[367,287,203,155],[425,331,241,177],[458,362,258,194],[520,412,292,220],[586,450,322,250],[644,504,364,280],[718,560,394,310],[792,624,442,338],[858,666,482,382],[929,711,509,403],[1003,779,565,439],[1091,857,611,461],[1171,911,661,511],[1273,997,715,535],[1367,1059,751,593],[1465,1125,805,
625],[1528,1190,868,658],[1628,1264,908,698],[1732,1370,982,742],[1840,1452,1030,790],[1952,1538,1112,842],[2068,1628,1168,898],[2188,1722,1228,958],[2303,1809,1283,983],[2431,1911,1351,1051],[2563,1989,1423,1093],[2699,2099,1499,1139],[2809,2213,1579,1219],[2953,2331,1663,1273]];E=function(){var e=function(g,h){this._el=g;this._htOption=h};return e.prototype.draw=function(g){function h(B,G){var C=document.createElementNS("http://www.w3.org/2000/svg",B),I;for(I in G)G.hasOwnProperty(I)&&C.setAttribute(I,
G[I]);return C}var f=this._htOption,m=this._el,u=g.getModuleCount();Math.floor(f.width/u);Math.floor(f.height/u);this.clear();var w=h("svg",{viewBox:"0 0 "+String(u)+" "+String(u),width:"100%",height:"100%",fill:f.colorLight});w.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:xlink","http://www.w3.org/1999/xlink");m.appendChild(w);w.appendChild(h("rect",{fill:f.colorDark,width:"1",height:"1",id:"template"}));for(f=0;u>f;f++)for(m=0;u>m;m++)if(g.isDark(f,m)){var t=h("use",{x:String(f),y:String(m)});
t.setAttributeNS("http://www.w3.org/1999/xlink","href","#template");w.appendChild(t)}},e.prototype.clear=function(){for(;this._el.hasChildNodes();)this._el.removeChild(this._el.lastChild)},e}();var T="svg"===document.documentElement.tagName.toLowerCase()?E:"undefined"!=typeof CanvasRenderingContext2D?function(){function e(){this._elImage.src=this._elCanvas.toDataURL("image/png");this._elImage.style.display="block";this._elCanvas.style.display="none"}function g(u,w){var t=this;if(t._fFail=w,t._fSuccess=
u,null===t._bSupportDataURI){var B=document.createElement("img"),G=function(){t._bSupportDataURI=!1;t._fFail&&_fFail.call(t)};return B.onabort=G,B.onerror=G,B.onload=function(){t._bSupportDataURI=!0;t._fSuccess&&t._fSuccess.call(t)},B.src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==",void 0}!0===t._bSupportDataURI&&t._fSuccess?t._fSuccess.call(t):!1===t._bSupportDataURI&&t._fFail&&t._fFail.call(t)}if(this._android&&
2.1>=this._android){var h=1/window.devicePixelRatio,f=CanvasRenderingContext2D.prototype.drawImage;CanvasRenderingContext2D.prototype.drawImage=function(u,w,t,B,G,C,I,K){if("nodeName"in u&&/img/i.test(u.nodeName))for(var L=arguments.length-1;1<=L;L--)arguments[L]*=h;else"undefined"==typeof K&&(arguments[1]*=h,arguments[2]*=h,arguments[3]*=h,arguments[4]*=h);f.apply(this,arguments)}}var m=function(u,w){this._bIsPainted=!1;this._android=n();this._htOption=w;this._elCanvas=document.createElement("canvas");
this._elCanvas.width=w.width;this._elCanvas.height=w.height;u.appendChild(this._elCanvas);this._el=u;this._oContext=this._elCanvas.getContext("2d");this._bIsPainted=!1;this._elImage=document.createElement("img");this._elImage.style.display="none";this._el.appendChild(this._elImage);this._bSupportDataURI=null};return m.prototype.draw=function(u){var w=this._elImage,t=this._oContext,B=this._htOption,G=u.getModuleCount(),C=B.width/G,I=B.height/G,K=Math.round(C),L=Math.round(I);w.style.display="none";
this.clear();for(w=0;G>w;w++)for(var O=0;G>O;O++){var R=u.isDark(w,O),Q=O*C,P=w*I;t.strokeStyle=R?B.colorDark:B.colorLight;t.lineWidth=1;t.fillStyle=R?B.colorDark:B.colorLight;t.fillRect(Q,P,C,I);t.strokeRect(Math.floor(Q)+.5,Math.floor(P)+.5,K,L);t.strokeRect(Math.ceil(Q)-.5,Math.ceil(P)-.5,K,L)}this._bIsPainted=!0},m.prototype.makeImage=function(){this._bIsPainted&&g.call(this,e)},m.prototype.isPainted=function(){return this._bIsPainted},m.prototype.clear=function(){this._oContext.clearRect(0,0,
this._elCanvas.width,this._elCanvas.height);this._bIsPainted=!1},m.prototype.round=function(u){return u?Math.floor(1E3*u)/1E3:u},m}():function(){var e=function(g,h){this._el=g;this._htOption=h};return e.prototype.draw=function(g){for(var h=this._htOption,f=this._el,m=g.getModuleCount(),u=Math.floor(h.width/m),w=Math.floor(h.height/m),t=['<table style="border:0;border-collapse:collapse;">'],B=0;m>B;B++){t.push("<tr>");for(var G=0;m>G;G++)t.push('<td style="border:0;border-collapse:collapse;padding:0;margin:0;width:'+
u+"px;height:"+w+"px;background-color:"+(g.isDark(B,G)?h.colorDark:h.colorLight)+';"></td>');t.push("</tr>")}t.push("</table>");f.textContent=t.join("");g=f.childNodes[0];f=(h.width-g.offsetWidth)/2;h=(h.height-g.offsetHeight)/2;0<f&&0<h&&(g.style.margin=h+"px "+f+"px")},e.prototype.clear=function(){this._el=""},e}();QRCode=function(e,g){if(this._htOption={width:256,height:256,typeNumber:4,colorDark:"#000000",colorLight:"#ffffff",correctLevel:y.H},"string"==typeof g&&(g={text:g}),g)for(var h in g)this._htOption[h]=
g[h];"string"==typeof e&&(e=document.getElementById(e));this._android=n();this._el=e;this._oQRCode=null;this._oDrawing=new T(this._el,this._htOption);this._htOption.text&&this.makeCode(this._htOption.text)};QRCode.prototype.makeCode=function(e){var g=this._htOption.correctLevel,h=1;var f=encodeURI(e).toString().replace(/%[0-9a-fA-F]{2}/g,"a");f=f.length+(f.length!=e?3:0);for(var m=0,u=J.length;u>=m;m++){var w=0;switch(g){case y.L:w=J[m][0];break;case y.M:w=J[m][1];break;case y.Q:w=J[m][2];break;case y.H:w=
J[m][3]}if(w>=f)break;h++}if(h>J.length)throw Error("Too long data");this._oQRCode=new c(h,this._htOption.correctLevel);this._oQRCode.addData(e);this._oQRCode.make();this._el.title=e;this._oDrawing.draw(this._oQRCode);this.makeImage()};QRCode.prototype.makeImage=function(){"function"==typeof this._oDrawing.makeImage&&(!this._android||3<=this._android)&&this._oDrawing.makeImage()};QRCode.prototype.clear=function(){this._oDrawing.clear()};QRCode.CorrectLevel=y}();var $jscomp=$jscomp||{};
$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,c){a.raw=c;return a};$jscomp.owns=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(a==Array.prototype||a==Object.prototype)return a;a[c]=b.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,c){var b=$jscomp.propertyToPolyfillSymbol[c];if(null==b)return a[c];b=a[b];return void 0!==b?b:a[c]};
$jscomp.polyfill=function(a,c,b,d){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,b,d):$jscomp.polyfillUnisolated(a,c,b,d))};$jscomp.polyfillUnisolated=function(a,c,b,d){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var k=a[d];if(!(k in b))return;b=b[k]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,b,d){var k=a.split(".");a=1===k.length;d=k[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var n=0;n<k.length-1;n++){var l=k[n];if(!(l in d))return;d=d[l]}k=k[k.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?d[k]:null;c=c(b);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,k,{configurable:!0,writable:!0,value:c}):c!==b&&(void 0===$jscomp.propertyToPolyfillSymbol[k]&&(b=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[k]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(k):$jscomp.POLYFILL_PREFIX+b+"$"+k),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[k],{configurable:!0,writable:!0,value:c})))};$jscomp.assign=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.assign?Object.assign:function(a,c){for(var b=1;b<arguments.length;b++){var d=arguments[b];if(d)for(var k in d)$jscomp.owns(d,k)&&(a[k]=d[k])}return a};
(function(){function a(r,z){var v=0,D=!1,x=window.setInterval(function(){r()&&(window.clearInterval(x),z(D));50<v++&&(window.clearInterval(x),D=!0,z(D))},10)}function c(r){r=r.toLowerCase();return 0===r.indexOf("msie")&&0===r.indexOf("trident")?!1:(r=/(?:msie|rv:)\s?([\d\.]+)/.exec(r))&&10<=parseInt(r[1],10)?!0:!1}function b(r){r=(r||q.userAgent).toLowerCase();return(r=r.match(/android\s([0-9\.]*)/))?r[1]:!1}function d(r,z){function v(H){if(H){console.log("candicate "+H);var S=t.exec(H);S&&(S=S[1],
H=H.match(w),void 0===x[S]&&r(S,H,!0),x[S]=!0)}else r()}function D(){N.localDescription.sdp.split("\n").forEach(function(H){H&&0===H.indexOf("a=candidate:")&&v(H)})}if("undefined"!==typeof document&&"function"===typeof document.getElementById){var x={},F=window.RTCPeerConnection||window.mozRTCPeerConnection||window.webkitRTCPeerConnection;if(!F){F=document.getElementById("iframe");if(!F)return;F=F.contentWindow;F=F.RTCPeerConnection||F.mozRTCPeerConnection||F.webkitRTCPeerConnection}if(F){var W=null;
"Chrome"===p.browser&&58>p.browser.version&&(W={optional:[{RtpDataChannels:!0}]});var N=new F({iceServers:[]},W);z&&(N.addStream?N.addStream(z):N.addTrack&&z.getTracks()[0]&&N.addTrack(z.getTracks()[0],z));N.onicecandidate=function(H){H.candidate&&H.candidate.candidate?v(H.candidate.candidate):v()};if(!z)try{N.createDataChannel("",{reliable:!1})}catch(H){}p.isPromisesSupported?N.createOffer().then(function(H){N.setLocalDescription(H).then(D)}):N.createOffer(function(H){N.setLocalDescription(H,D,function(){})},
function(){})}}}function k(r){if(L)if(!q.enumerateDevices&&window.MediaStreamTrack&&window.MediaStreamTrack.getSources&&(q.enumerateDevices=window.MediaStreamTrack.getSources.bind(window.MediaStreamTrack)),!q.enumerateDevices&&q.enumerateDevices&&(q.enumerateDevices=q.enumerateDevices.bind(q)),q.enumerateDevices){G=[];C=[];I=[];K=[];U=P=Q=R=O=!1;var z={};q.enumerateDevices(function(v){G=[];C=[];I=[];K=[];v.forEach(function(D){var x={},F;for(F in D)try{"function"!==typeof D[F]&&(x[F]=D[F])}catch(W){}z[x.deviceId+
x.label+x.kind]||("audio"===x.kind&&(x.kind="audioinput"),"video"===x.kind&&(x.kind="videoinput"),x.deviceId||(x.deviceId=x.id),x.id||(x.id=x.deviceId),x.label?("videoinput"!==x.kind||U||(U=!0),"audioinput"!==x.kind||P||(P=!0)):(x.isCustomLabel=!0,x.label="videoinput"===x.kind?"Camera "+(K.length+1):"audioinput"===x.kind?"Microphone "+(C.length+1):"audiooutput"===x.kind?"Speaker "+(I.length+1):"Please invoke getUserMedia once.","undefined"!==typeof p&&p.browser.isChrome&&46<=p.browser.version&&!/^(https:|chrome-extension:)$/g.test(location.protocol||
"")&&"undefined"!==typeof document&&"string"===typeof document.domain&&document.domain.search&&-1===document.domain.search(/localhost|127.0./g)&&(x.label="HTTPs is required to get label of this "+x.kind+" device.")),"audioinput"===x.kind&&(O=!0,-1===C.indexOf(x)&&C.push(x)),"audiooutput"===x.kind&&(R=!0,-1===I.indexOf(x)&&I.push(x)),"videoinput"===x.kind&&(Q=!0,-1===K.indexOf(x)&&K.push(x)),G.push(x),z[x.deviceId+x.label+x.kind]=x)});"undefined"!==typeof p&&(p.MediaDevices=G,p.hasMicrophone=O,p.hasSpeakers=
R,p.hasWebcam=Q,p.isWebsiteHasWebcamPermissions=U,p.isWebsiteHasMicrophonePermissions=P,p.audioInputDevices=C,p.audioOutputDevices=I,p.videoInputDevices=K);r&&r()})}else r&&r();else r&&r()}var n="Fake/5.0 (FakeOS) AppleWebKit/123 (KHTML, like Gecko) Fake/12.3.4567.89 Fake/123.45",l="object"===typeof process&&"object"===typeof process.versions&&process.versions.node&&!process.browser;if(l){var y=process.versions.node.toString().replace("v","");n="Nodejs/"+y+" (NodeOS) AppleWebKit/"+y+" (KHTML, like Gecko) Nodejs/"+
y+" Nodejs/"+y}(function(r){"undefined"===typeof window&&("undefined"===typeof window&&"undefined"!==typeof global?(global.navigator={userAgent:n,getUserMedia:function(){}},r.window=global):"undefined"===typeof window&&console.log("window undefined"),"undefined"===typeof location&&(r.location={protocol:"file:",href:"",hash:""}),"undefined"===typeof screen&&(r.screen={width:0,height:0}))})("undefined"!==typeof global?global:window);var q=window.navigator;"undefined"!==typeof q?("undefined"!==typeof q.webkitGetUserMedia&&
(q.getUserMedia=q.webkitGetUserMedia),"undefined"!==typeof q.mozGetUserMedia&&(q.getUserMedia=q.mozGetUserMedia)):q={getUserMedia:function(){},userAgent:n};y=!!/Android|webOS|iPhone|iPad|iPod|BB10|BlackBerry|IEMobile|Opera Mini|Mobile|mobile/i.test(q.userAgent||"");var A=-1!==q.userAgent.indexOf("Edge")&&(!!q.msSaveOrOpenBlob||!!q.msSaveBlob),E=!!window.opera||0<=q.userAgent.indexOf(" OPR/"),J=-1<q.userAgent.toLowerCase().indexOf("firefox")&&"netscape"in window&&/ rv:/.test(q.userAgent),T=/^((?!chrome|android).)*safari/i.test(q.userAgent),
e=!!window.chrome&&!E,g={Android:function(){return q.userAgent.match(/Android/i)},BlackBerry:function(){return q.userAgent.match(/BlackBerry|BB10/i)},iOS:function(){return q.userAgent.match(/iPhone|iPad|iPod/i)},Opera:function(){return q.userAgent.match(/Opera Mini/i)},Windows:function(){return q.userAgent.match(/IEMobile/i)},any:function(){return g.Android()||g.BlackBerry()||g.iOS()||g.Opera()||g.Windows()},getOsName:function(){var r="Unknown OS";g.Android()&&(r="Android");g.BlackBerry()&&(r="BlackBerry");
g.iOS()&&(r="iOS");g.Opera()&&(r="Opera Mini");g.Windows()&&(r="Windows");return r}},h="Unknown OS",f="Unknown OS Version";(l=function(){for(var r=q.appVersion,z=q.userAgent,v="-",D=[{s:"Chrome OS",r:/CrOS/},{s:"Windows 10",r:/(Windows 10.0|Windows NT 10.0)/},{s:"Windows 8.1",r:/(Windows 8.1|Windows NT 6.3)/},{s:"Windows 8",r:/(Windows 8|Windows NT 6.2)/},{s:"Windows 7",r:/(Windows 7|Windows NT 6.1)/},{s:"Windows Vista",r:/Windows NT 6.0/},{s:"Windows Server 2003",r:/Windows NT 5.2/},{s:"Windows XP",
r:/(Windows NT 5.1|Windows XP)/},{s:"Windows 2000",r:/(Windows NT 5.0|Windows 2000)/},{s:"Windows ME",r:/(Win 9x 4.90|Windows ME)/},{s:"Windows 98",r:/(Windows 98|Win98)/},{s:"Windows 95",r:/(Windows 95|Win95|Windows_95)/},{s:"Windows NT 4.0",r:/(Windows NT 4.0|WinNT4.0|WinNT|Windows NT)/},{s:"Windows CE",r:/Windows CE/},{s:"Windows 3.11",r:/Win16/},{s:"Android",r:/Android/},{s:"Open BSD",r:/OpenBSD/},{s:"Sun OS",r:/SunOS/},{s:"Linux",r:/(Linux|X11)/},{s:"iOS",r:/(iPhone|iPad|iPod)/},{s:"Mac OS X",
r:/Mac OS X/},{s:"Mac OS",r:/(MacPPC|MacIntel|Mac_PowerPC|Macintosh)/},{s:"QNX",r:/QNX/},{s:"UNIX",r:/UNIX/},{s:"BeOS",r:/BeOS/},{s:"OS/2",r:/OS\/2/},{s:"Search Bot",r:/(nuhk|Googlebot|Yammybot|Openbot|Slurp|MSNBot|Ask Jeeves\/Teoma|ia_archiver)/}],x=0,F;F=D[x];x++)if(F.r.test(z)){v=F.s;break}D="-";/Windows/.test(v)&&(/Windows (.*)/.test(v)&&(D=/Windows (.*)/.exec(v)[1]),v="Windows");switch(v){case "Mac OS X":/Mac OS X (10[\._\d]+)/.test(z)&&(D=/Mac OS X (10[\._\d]+)/.exec(z)[1]);break;case "Android":/Android ([\._\d]+)/.test(z)&&
(D=/Android ([\._\d]+)/.exec(z)[1]);break;case "iOS":/OS (\d+)_(\d+)_?(\d+)?/.test(z)&&(D=/OS (\d+)_(\d+)_?(\d+)?/.exec(r))&&3<D.length&&(D=D[1]+"."+D[2]+"."+(D[3]|0))}return{osName:v,osVersion:D}}())&&l.osName&&"-"!=l.osName?(h=l.osName,f=l.osVersion):g.any()&&(h=g.getOsName(),"Android"==h&&(f=b()));l="object"===typeof process&&"object"===typeof process.versions&&process.versions.node;"Unknown OS"===h&&l&&(h="Nodejs",f=process.versions.node.toString().replace("v",""));var m=!1,u=!1;["captureStream",
"mozCaptureStream","webkitCaptureStream"].forEach(function(r){"undefined"!==typeof document&&"function"===typeof document.createElement&&(!m&&r in document.createElement("canvas")&&(m=!0),!u&&r in document.createElement("video")&&(u=!0))});var w=/^(192\.168\.|169\.254\.|10\.|172\.(1[6-9]|2\d|3[01]))/,t=/([0-9]{1,3}(\.[0-9]{1,3}){3})/,B=/[a-f0-9]{1,4}(:[a-f0-9]{1,4}){7}/,G=[],C=[],I=[],K=[];q.mediaDevices&&q.mediaDevices.enumerateDevices&&(q.enumerateDevices=function(r){var z=q.mediaDevices.enumerateDevices();
z&&z.then?q.mediaDevices.enumerateDevices().then(r)["catch"](function(){r([])}):r([])});var L=!1;"undefined"!==typeof MediaStreamTrack&&"getSources"in MediaStreamTrack?L=!0:q.mediaDevices&&q.mediaDevices.enumerateDevices&&(L=!0);var O=!1,R=!1,Q=!1,P=!1,U=!1,p=window.DetectRTC||{};p.browser=function(){var r=q.userAgent,z=q.appName,v=""+parseFloat(q.appVersion);parseInt(q.appVersion,10);var D,x;if(E){z="Opera";try{v=q.userAgent.split("OPR/")[1].split(" ")[0],v.split(".")}catch(W){v="0.0.0.0"}}else if(e){var F=
r.indexOf("Chrome");z="Chrome";v=r.substring(F+7)}else T?-1!==r.indexOf("CriOS")?(F=r.indexOf("CriOS"),z="Chrome",v=r.substring(F+6)):-1!==r.indexOf("FxiOS")?(F=r.indexOf("FxiOS"),z="Firefox",v=r.substring(F+6)):(F=r.indexOf("Safari"),z="Safari",v=r.substring(F+7),-1!==(F=r.indexOf("Version"))&&(v=r.substring(F+8)),-1!==q.userAgent.indexOf("Version/")&&(v=q.userAgent.split("Version/")[1].split(" ")[0])):J?(F=r.indexOf("Firefox"),z="Firefox",v=r.substring(F+8)):(D=r.lastIndexOf(" ")+1)<(F=r.lastIndexOf("/"))&&
(z=r.substring(D,F),v=r.substring(F+1),z.toLowerCase()===z.toUpperCase()&&(z=q.appName));A&&(z="Edge",v=q.userAgent.split("Edge/")[1]);-1!==(x=v.search(/[; \)]/))&&(v=v.substring(0,x));r=parseInt(""+v,10);isNaN(r)&&(v=""+parseFloat(q.appVersion),r=parseInt(q.appVersion,10));return{fullVersion:v,version:r,name:z,isPrivateBrowsing:!1}}();(function(r){try{if(window.webkitRequestFileSystem)window.webkitRequestFileSystem(window.TEMPORARY,1,function(){v=!1},function(D){v=!0});else if(window.indexedDB&&
/Firefox/.test(window.navigator.userAgent)){try{var z=window.indexedDB.open("test");z.onerror=function(){return!0}}catch(D){var v=!0}"undefined"===typeof v&&a(function(){return"done"===z.readyState?!0:!1},function(D){D||(v=z.result?!1:!0)})}else if(c(window.navigator.userAgent)){v=!1;try{window.indexedDB||(v=!0)}catch(D){v=!0}}else if(window.localStorage&&/Safari/.test(window.navigator.userAgent)){try{window.localStorage.setItem("test",1)}catch(D){v=!0}"undefined"===typeof v&&(v=!1,window.localStorage.removeItem("test"))}}catch(D){v=
!1}a(function(){return"undefined"!==typeof v?!0:!1},function(D){r(v)})})(function(r){p.browser.isPrivateBrowsing=!!r});p.browser["is"+p.browser.name]=!0;p.osName=h;p.osVersion=f;var Z=!1;["RTCPeerConnection","webkitRTCPeerConnection","mozRTCPeerConnection","RTCIceGatherer"].forEach(function(r){Z||r in window&&(Z=!0)});p.isWebRTCSupported=Z;p.isORTCSupported="undefined"!==typeof RTCIceGatherer;h=!1;p.browser.isChrome&&35<=p.browser.version?h=!0:p.browser.isFirefox&&34<=p.browser.version?h=!0:p.browser.isEdge&&
17<=p.browser.version?h=!0:"Android"===p.osName&&p.browser.isChrome&&(h=!0);if(q.getDisplayMedia||q.mediaDevices&&q.mediaDevices.getDisplayMedia)h=!0;/^(https:|chrome-extension:)$/g.test(location.protocol||"")||("undefined"!==typeof document&&"string"===typeof document.domain&&document.domain.search&&-1===document.domain.search(/localhost|127.0./g)&&(p.browser.isChrome||p.browser.isEdge||p.browser.isOpera)?h=!1:p.browser.isFirefox&&(h=!1));p.isScreenCapturingSupported=h;var aa=!1,ba=!1;["AudioContext",
"webkitAudioContext","mozAudioContext","msAudioContext"].forEach(function(r){!aa&&r in window&&(aa=!0,window[r]&&"createMediaStreamSource"in window[r].prototype&&(ba=!0))});p.isAudioContextSupported=aa;p.isCreateMediaStreamSourceSupported=ba;h=!1;p.browser.isChrome&&31<p.browser.version&&(h=!0);p.isRtpDataChannelsSupported=h;h=!1;p.browser.isFirefox&&28<p.browser.version?h=!0:p.browser.isChrome&&25<p.browser.version?h=!0:p.browser.isOpera&&11<=p.browser.version&&(h=!0);p.isSctpDataChannelsSupported=
h;p.isMobileDevice=y;y=!1;q.getUserMedia?y=!0:q.mediaDevices&&q.mediaDevices.getUserMedia&&(y=!0);p.browser.isChrome&&46<=p.browser.version&&!/^(https:|chrome-extension:)$/g.test(location.protocol||"")&&"undefined"!==typeof document&&"string"===typeof document.domain&&document.domain.search&&-1===document.domain.search(/localhost|127.0./g)&&(y="Requires HTTPs");"Nodejs"===p.osName&&(y=!1);p.isGetUserMediaSupported=y;y="";screen.width&&(y+=""+(screen.width?screen.width:"")+" x "+(screen.height?screen.height:
""));p.displayResolution=y;p.displayAspectRatio=function(r,z){function v(x,F){return 0==F?x:v(F,x%F)}var D=v(r,z);return r/D/(z/D)}(screen.width,screen.height).toFixed(2);p.isCanvasSupportsStreamCapturing=m;p.isVideoSupportsStreamCapturing=u;"Chrome"==p.browser.name&&53<=p.browser.version&&(p.isCanvasSupportsStreamCapturing||(p.isCanvasSupportsStreamCapturing="Requires chrome flag: enable-experimental-web-platform-features"),p.isVideoSupportsStreamCapturing||(p.isVideoSupportsStreamCapturing="Requires chrome flag: enable-experimental-web-platform-features"));
p.DetectLocalIPAddress=function(r,z){if(p.isWebRTCSupported){var v=!0,D=!0;d(function(x){x?x.match(w)?(v=!1,r("Local: "+x,v,D)):(x.match(B)&&(D=!1),r("Public: "+x,v,D)):r()},z)}};p.isWebSocketsSupported="WebSocket"in window&&2===window.WebSocket.CLOSING;p.isWebSocketsBlocked=!p.isWebSocketsSupported;"Nodejs"===p.osName&&(p.isWebSocketsSupported=!0,p.isWebSocketsBlocked=!1);p.checkWebSocketsSupport=function(r){r=r||function(){};try{var z,v=new WebSocket("wss://echo.websocket.org:443/");v.onopen=function(){p.isWebSocketsBlocked=
!1;z=(new Date).getTime();v.send("ping")};v.onmessage=function(){p.WebsocketLatency=(new Date).getTime()-z+"ms";r();v.close();v=null};v.onerror=function(){p.isWebSocketsBlocked=!0;r()}}catch(D){p.isWebSocketsBlocked=!0,r()}};p.load=function(r){k(r||function(){})};"function"===typeof k&&console.log("check device support !");p.MediaDevices="undefined"!==typeof G?G:[];p.hasMicrophone=O;p.hasSpeakers=R;p.hasWebcam=Q;p.isWebsiteHasWebcamPermissions=U;p.isWebsiteHasMicrophonePermissions=P;p.audioInputDevices=
C;p.audioOutputDevices=I;p.videoInputDevices=K;y=!1;"undefined"!==typeof document&&"function"===typeof document.createElement&&"setSinkId"in document.createElement("video")&&(y=!0);p.isSetSinkIdSupported=y;y=!1;p.browser.isFirefox&&"undefined"!==typeof mozRTCPeerConnection?"getSenders"in mozRTCPeerConnection.prototype&&(y=!0):p.browser.isChrome&&"undefined"!==typeof webkitRTCPeerConnection&&"getSenders"in webkitRTCPeerConnection.prototype&&(y=!0);p.isRTPSenderReplaceTracksSupported=y;y=!1;p.browser.isFirefox&&
38<p.browser.version&&(y=!0);p.isRemoteStreamProcessingSupported=y;y=!1;"undefined"!==typeof MediaStreamTrack&&"applyConstraints"in MediaStreamTrack.prototype&&(y=!0);p.isApplyConstraintsSupported=y;y=!1;p.browser.isFirefox&&43<=p.browser.version&&(y=!0);p.isMultiMonitorScreenCapturingSupported=y;p.isPromisesSupported=!!("Promise"in window);p.version="1.4.1";"undefined"===typeof p&&(window.DetectRTC={});y=window.MediaStream;"undefined"===typeof y&&"undefined"!==typeof webkitMediaStream&&(y=webkitMediaStream);
p.MediaStream="undefined"!==typeof y&&"function"===typeof y?Object.keys(y.prototype):!1;p.MediaStreamTrack="undefined"!==typeof MediaStreamTrack?Object.keys(MediaStreamTrack.prototype):!1;y=window.RTCPeerConnection||window.mozRTCPeerConnection||window.webkitRTCPeerConnection;p.RTCPeerConnection="undefined"!==typeof y?Object.keys(y.prototype):!1;window.DetectRTC=p;"undefined"!==typeof module&&(module.exports=p);"function"===typeof define&&define.amd&&define("DetectRTC",[],function(){return p})})();
var cc=cc||{};
cc.defineGetterSetter=function(a,c,b,d,k,n){if(a.__defineGetter__)b&&a.__defineGetter__(c,b),d&&a.__defineSetter__(c,d);else if(Object.defineProperty){var l={enumerable:!1,configurable:!0};b&&(l.get=b);d&&(l.set=d);Object.defineProperty(a,c,l)}else throw Error("browser does not support getters");if(!k&&!n){l=null!=b;for(var y=void 0!=d,q=Object.getOwnPropertyNames(a),A=0;A<q.length;A++){var E=q[A];if((a.__lookupGetter__?!a.__lookupGetter__(E):!Object.getOwnPropertyDescriptor(a,E))&&"function"===typeof a[E]){var J=
a[E];if(l&&J===b&&(k=E,!y||n))break;if(y&&J===d&&(n=E,!l||k))break}}}a=a.constructor;k&&(a.__getters__||(a.__getters__={}),a.__getters__[k]=c);n&&(a.__setters__||(a.__setters__={}),a.__setters__[n]=c)};cc.clone=function(a){var c=a.constructor?new a.constructor:{},b;for(b in a){var d=a[b];c[b]="object"!==typeof d||!d||d instanceof cc.Node||d instanceof HTMLElement?d:cc.clone(d)}return c};cc.inject=function(a,c){for(var b in a)c[b]=a[b]};
var ClassManager=function(){var a=0|998*Math.random(),c=0|998*Math.random();this.getNewID=function(){return a++};this.getNewInstanceId=function(){return c++}},classManager=new ClassManager;
(function(){var a=/\b_super\b/;cc.Class=function(){};cc.Class.extend=function(c){cc.isEmpty(c._html)||cc["import"](c._html);cc.isEmpty(c._css)||cc["import"](c._css);var b=this.prototype,d=Object.create(b),k={writable:!0,enumerable:!1,configurable:!0};var n=function(f,m,u,w,t){this.__instanceId=classManager.getNewInstanceId();if(this.ctor)switch(arguments.length){case 0:this.ctor();break;case 1:this.ctor(f);break;case 2:this.ctor(f,m);break;case 3:this.ctor(f,m,u);break;case 4:this.ctor(f,m,u,w);break;
case 5:this.ctor(f,m,u,w,t);break;default:this.ctor.apply(this,arguments)}};k.value=classManager.getNewID();Object.defineProperty(d,"__pid",k);n.prototype=d;k.value=n;Object.defineProperty(d,"constructor",k);this.__getters__&&(n.__getters__=cc.clone(this.__getters__));this.__setters__&&(n.__setters__=cc.clone(this.__setters__));for(var l=0,y=arguments.length;l<y;++l){var q=arguments[l],A;for(A in q){var E="function"===typeof q[A],J="function"===typeof b[A],T=a.test(q[A]);E&&J&&T?(k.value=function(f,
m){return function(){var u=this._super;this._super=b[f];var w=m.apply(this,arguments);this._super=u;return w}}(A,q[A]),Object.defineProperty(d,A,k)):E?(k.value=q[A],Object.defineProperty(d,A,k)):d[A]=q[A];if(E){if(this.__getters__&&this.__getters__[A]){E=this.__getters__[A];for(var e in this.__setters__)if(this.__setters__[e]===E){var g=e;break}cc.defineGetterSetter(d,E,q[A],q[g]?q[g]:d[g],A,g)}if(this.__setters__&&this.__setters__[A]){E=this.__setters__[A];for(e in this.__getters__)if(this.__getters__[e]===
E){var h=e;break}cc.defineGetterSetter(d,E,q[h]?q[h]:d[h],q[A],h,A)}}}}n.extend=cc.Class.extend;n.implement=function(f){for(var m in f)d[m]=f[m]};return n}})();cc.each=function(a,c,b){if(a)if(a instanceof Array)for(var d=0,k=a.length;d<k&&!1!==c.call(b,a[d],d);d++);else for(d in a)if(!1===c.call(b,a[d],d))break};cc.extend=function(a){var c=2<=arguments.length?Array.prototype.slice.call(arguments,1):[];cc.each(c,function(b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])});return a};
cc.inherits=function(a,c){function b(){}b.prototype=c.prototype;a.superClass_=c.prototype;a.prototype=new b;a.prototype.constructor=a};cc.isFunction=function(a){return"function"===typeof a};cc.isNumber=function(a){return"number"===typeof a||"[object Number]"===Object.prototype.toString.call(a)};cc.isString=function(a){return"string"===typeof a||"[object String]"===Object.prototype.toString.call(a)};cc.isArray=function(a){return Array.isArray(a)||"object"===typeof a&&"[object Array]"===Object.prototype.toString.call(a)};
cc.isUndefined=function(a){return"undefined"===typeof a};cc.isObject=function(a){return"object"===typeof a&&"[object Object]"===Object.prototype.toString.call(a)};cc.objToArray=function(a){var c=[],b;for(b in a)c.push(a[b]);return c};cc.localLog={maxLog:20,isLocalStorage:window.localStorage?!0:!1,push:function(a){},send:function(a,c){}};cc.log=function(a){var c=(new Date).toISOString();a=c.substr(c.length-13,13)+"--"+a;console.log(a)};
cc.isEmpty=function(a){return void 0==a||null==a||""==a.toString()?!0:!1};String.prototype.replaceAll=function(a,c){return this.replace(new RegExp(a,"g"),c)};cc.Class.prototype.addCEventListener=function(a,c,b){null==this.arrEventCb&&(this.arrEventCb=[]);for(var d=!1,k=0;k<this.arrEventCb.length;k++)if(this.arrEventCb[k].ev==a&&this.arrEventCb[k].cb==c&&this.arrEventCb[k].caller==b){d=!0;break}d||this.arrEventCb.push({ev:a,cb:c,caller:b})};
cc.Class.prototype.removeCEventListener=function(a,c,b){null==this.arrEventCb&&(this.arrEventCb=[]);for(var d=0;d<this.arrEventCb.length;d++)if(this.arrEventCb[d].ev==a&&this.arrEventCb[d].cb==c&&b==this.arrEventCb[d].caller){this.arrEventCb.splice(d,1);break}};cc.Class.prototype.CEventCallback=function(a){if(null!=this.arrEventCb)for(var c=this.arrEventCb.concat(),b=0;b<c.length;b++)c[b].ev==a&&c[b].cb.apply(c[b].caller,arguments)};
cc.Class.prototype.dispath=function(a){if(null!=this.arrEventCb)for(var c=this.arrEventCb.concat(),b=0;b<c.length;b++)c[b].ev==a&&c[b].cb.apply(c[b].caller,arguments)};cc.Class.prototype.removeAllCEventListener=function(a){if(null==a)null!=this.arrEventCb&&(this.arrEventCb=[]);else if(null!=this.arrEventCb&&void 0!=this.arrEventCb){do{var c=!1;for(var b=0;b<this.arrEventCb.length;b++)if(this.arrEventCb[b].ev==a){this.arrEventCb.splice(b,1);c=!0;break}}while(c)}};
cc.os=function(){var a=navigator.userAgent.toLowerCase(),c=/iphone|ipod|ipad/.test(a);return/android/.test(a)?"android":c?"ios":"pc"};cc.isMobile=function(){var a=cc.os();return"android"==a||"ios"==a?!0:!1};cc.isWebview=function(){return"zaloWebview"==cc.browserName||"fbWebview"==cc.browserName||"webview"==cc.browserName?!0:!1};
cc.browserName=function(){var a=navigator.userAgent.toLowerCase();if(0<=a.indexOf("zalo"))return"zaloWebview";if(0<=a.indexOf("FBAV"))return"fbWebview";if(0<=a.indexOf("webview"))return"webview";if(0<=a.indexOf("coccoc"))return"coccoc";var c="undefined"!==typeof InstallTrigger,b=/constructor/i.test(window.HTMLElement)||"[object SafariRemoteNotification]"===(!window.safari||"undefined"!==typeof safari&&window.safari.pushNotification).toString();0<=a.indexOf("safari")&&(b=!0);a=!!window.StyleMedia;
var d=-1!=navigator.userAgent.indexOf("Chrome"),k=d&&-1!=navigator.userAgent.indexOf("Edg");return b?"safari":c?"firefox":a?"edge":d?"chrome":k?"edgeChrome":"other"};cc.touchable=function(){return"ontouchstart"in window||navigator.msMaxTouchPoints};cc.webrtcSupport=function(){return navigator.mediaDevices&&navigator.mediaDevices.getUserMedia&&navigator.mediaDevices.enumerateDevices&&"undefined"!=typeof RTCPeerConnection?!0:!1};
cc.mediaRecorderSupport=function(){return navigator.mediaDevices&&navigator.mediaDevices.getUserMedia&&window.MediaRecorder?!0:!1};cc.workerSupport=function(){return"undefined"!==typeof Worker?!0:!1};
cc.fullscreenSupport=function(){var a=document.body;return"undefined"!==typeof a.requestFullscreen||"undefined"!==typeof a.mozRequestFullScreen||"undefined"!==typeof a.webkitRequestFullscreen||"undefined"!==typeof a.msRequestFullscreen||"undefined"!==typeof document.exitFullscreen||"undefined"!==typeof document.mozCancelFullScreen||"undefined"!==typeof document.webkitExitFullscreen};cc.removeAllChildNodes=function(a){if(a)for(;a.firstChild;)a.removeChild(a.firstChild)};
cc.removeDomAttr=function(a,c){if(cc.isArray(c)&&a&&a instanceof HTMLElement)for(var b=0;b<c.length;b++)a.removeAttribute(c[b])};cc.getAttrToNumber=function(a,c){return Number(a.getAttribute(c))};cc.createGrid=function(a,c){if(0>=a||0>=c)return null;for(var b=document.createElement("div"),d=100/a,k=100/c,n=0;n<a*c;n++){var l=document.createElement("div");l.style.width=k+"%";l.style.height=d+"%";l.style.position="relative";l.style["float"]="left";l.setAttribute("grid",n);b.appendChild(l)}return b};
cc.dragDom=null;cc.winSize=function(){return{width:window.innerWidth,height:window.innerHeight}};cc.getParameterByName=function(a,c){c=void 0===c?window.location.href:c;a=a.replace(/[\[\]]/g,"\\$&");var b=(new RegExp("[?&]"+a+"(=([^&#]*)|&|#|$)")).exec(c);return b?b[2]?decodeURIComponent(b[2].replace(/\+/g," ")):"":null};cc.appVer=.1;
cc.loadCss=function(a){for(var c=0;c<a.length;c++){var b=document.getElementsByTagName("HEAD")[0],d=document.createElement("link");d.rel="stylesheet";d.type="text/css";d.href=a[c]+"?ver="+cc.appVer;b.appendChild(d)}};cc.insertCss=function(a){var c=document.createElement("style");c.type="text/css";c.textContent=a;document.getElementsByTagName("head")[0].appendChild(c)};
cc.getText=function(a,c){if(a)try{var b=new XMLHttpRequest;b.onreadystatechange=function(){4==this.readyState&&(200==this.status?c&&c(!0,this.responseText):c(!1,this.status))};b.open("GET",a+"?ver="+cc.appVer);b.send()}catch(d){c(!1,d.toString())}};
cc.getJson=function(a,c){if(a)try{var b=new XMLHttpRequest;b.onreadystatechange=function(){if(4==this.readyState)if(200==this.status){if(c)try{c(!0,JSON.parse(this.responseText))}catch(d){c(!1,"error parse json result "+this.responseText)}}else c(!1,this.status)};b.open("GET",a+"?ver="+cc.appVer);b.send()}catch(d){c(!1,d.toString())}};
cc.loadJs=function(a,c,b){cc.isString(a)&&(a=[a]);if(!cc.isNumber(b)||0>b)b=0;if(a&&cc.isArray(a))if(a.length<=b)c&&c.call(null,!0);else{var d=a[b],k=document.createElement("script");k.onload=function(){b<a.length&&(b++,cc.loadJs(a,c,b))};k.onerror=function(){c&&c.call(null,!1)};k.src=d+"?ver="+cc.appVer;k.async=!0;document.body.appendChild(k)}};
cc.loadHtml=function(a,c,b){if(!cc.isNumber(b)||0>b)b=0;a&&cc.isArray(a)&&(a.length<=b?c&&c.call(null,!0):cc.getText(a[b],function(d,k){d&&(cc.htmlImport[a[b]]=k);b++;cc.loadHtml(a,c,b)}))};cc.randomStr=function(a){for(var c="",b=0;b<a;b++)c+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return c};cc.jsfw=[];cc.coreready=null;cc.callbackready=null;cc.onready=function(a){null==cc.coreready?cc.callbackready=a:a.call(null,cc.coreready)};
cc.loadJs(cc.jsfw,function(a){cc.coreready=a;cc.callbackready&&cc.callbackready.call(null,cc.coreready)});cc.htmlImport={};cc.cssImport={};cc.getHtml=function(a){return cc.htmlImport[a]?cc.htmlImport[a]:""};cc["import"]=function(a){0<a.indexOf(".css")&&(cc.cssImport[a]||(cc.cssImport[a]=a));0<a.indexOf(".html")&&(cc.htmlImport[a]||(cc.htmlImport[a]=a))};cc.initApp=function(a,c){cc.loadJs(a,function(b){cc.loadCss(cc.objToArray(cc.cssImport));cc.loadHtml(cc.objToArray(cc.htmlImport),function(){c&&c()})})};
cc.randomUUID=function(){var a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var b=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"==c?b:b&3|8).toString(16)})};cc.md5=function(a){return M(V(Y(X(a),8*a.length))).toLowerCase()};function M(a){for(var c,b="",d=0;d<a.length;d++)c=a.charCodeAt(d),b+="0123456789ABCDEF".charAt(c>>>4&15)+"0123456789ABCDEF".charAt(15&c);return b}
function X(a){for(var c=Array(a.length>>2),b=0;b<c.length;b++)c[b]=0;for(b=0;b<8*a.length;b+=8)c[b>>5]|=(255&a.charCodeAt(b/8))<<b%32;return c}function V(a){for(var c="",b=0;b<32*a.length;b+=8)c+=String.fromCharCode(a[b>>5]>>>b%32&255);return c}
function Y(a,c){a[c>>5]|=128<<c%32;a[14+(c+64>>>9<<4)]=c;for(var b=1732584193,d=-271733879,k=-1732584194,n=271733878,l=0;l<a.length;l+=16){var y=b,q=d,A=k,E=n;d=md5_ii(d=md5_ii(d=md5_ii(d=md5_ii(d=md5_hh(d=md5_hh(d=md5_hh(d=md5_hh(d=md5_gg(d=md5_gg(d=md5_gg(d=md5_gg(d=md5_ff(d=md5_ff(d=md5_ff(d=md5_ff(d,k=md5_ff(k,n=md5_ff(n,b=md5_ff(b,d,k,n,a[l+0],7,-680876936),d,k,a[l+1],12,-389564586),b,d,a[l+2],17,606105819),n,b,a[l+3],22,-1044525330),k=md5_ff(k,n=md5_ff(n,b=md5_ff(b,d,k,n,a[l+4],7,-176418897),
d,k,a[l+5],12,1200080426),b,d,a[l+6],17,-1473231341),n,b,a[l+7],22,-45705983),k=md5_ff(k,n=md5_ff(n,b=md5_ff(b,d,k,n,a[l+8],7,1770035416),d,k,a[l+9],12,-1958414417),b,d,a[l+10],17,-42063),n,b,a[l+11],22,-1990404162),k=md5_ff(k,n=md5_ff(n,b=md5_ff(b,d,k,n,a[l+12],7,1804603682),d,k,a[l+13],12,-40341101),b,d,a[l+14],17,-1502002290),n,b,a[l+15],22,1236535329),k=md5_gg(k,n=md5_gg(n,b=md5_gg(b,d,k,n,a[l+1],5,-165796510),d,k,a[l+6],9,-1069501632),b,d,a[l+11],14,643717713),n,b,a[l+0],20,-373897302),k=md5_gg(k,
n=md5_gg(n,b=md5_gg(b,d,k,n,a[l+5],5,-701558691),d,k,a[l+10],9,38016083),b,d,a[l+15],14,-660478335),n,b,a[l+4],20,-405537848),k=md5_gg(k,n=md5_gg(n,b=md5_gg(b,d,k,n,a[l+9],5,568446438),d,k,a[l+14],9,-1019803690),b,d,a[l+3],14,-187363961),n,b,a[l+8],20,1163531501),k=md5_gg(k,n=md5_gg(n,b=md5_gg(b,d,k,n,a[l+13],5,-1444681467),d,k,a[l+2],9,-51403784),b,d,a[l+7],14,1735328473),n,b,a[l+12],20,-1926607734),k=md5_hh(k,n=md5_hh(n,b=md5_hh(b,d,k,n,a[l+5],4,-378558),d,k,a[l+8],11,-2022574463),b,d,a[l+11],16,
1839030562),n,b,a[l+14],23,-35309556),k=md5_hh(k,n=md5_hh(n,b=md5_hh(b,d,k,n,a[l+1],4,-1530992060),d,k,a[l+4],11,1272893353),b,d,a[l+7],16,-155497632),n,b,a[l+10],23,-1094730640),k=md5_hh(k,n=md5_hh(n,b=md5_hh(b,d,k,n,a[l+13],4,681279174),d,k,a[l+0],11,-358537222),b,d,a[l+3],16,-722521979),n,b,a[l+6],23,76029189),k=md5_hh(k,n=md5_hh(n,b=md5_hh(b,d,k,n,a[l+9],4,-640364487),d,k,a[l+12],11,-421815835),b,d,a[l+15],16,530742520),n,b,a[l+2],23,-995338651),k=md5_ii(k,n=md5_ii(n,b=md5_ii(b,d,k,n,a[l+0],6,
-198630844),d,k,a[l+7],10,1126891415),b,d,a[l+14],15,-1416354905),n,b,a[l+5],21,-57434055),k=md5_ii(k,n=md5_ii(n,b=md5_ii(b,d,k,n,a[l+12],6,1700485571),d,k,a[l+3],10,-1894986606),b,d,a[l+10],15,-1051523),n,b,a[l+1],21,-2054922799),k=md5_ii(k,n=md5_ii(n,b=md5_ii(b,d,k,n,a[l+8],6,1873313359),d,k,a[l+15],10,-30611744),b,d,a[l+6],15,-1560198380),n,b,a[l+13],21,1309151649),k=md5_ii(k,n=md5_ii(n,b=md5_ii(b,d,k,n,a[l+4],6,-145523070),d,k,a[l+11],10,-1120210379),b,d,a[l+2],15,718787259),n,b,a[l+9],21,-343485551);
b=safe_add(b,y);d=safe_add(d,q);k=safe_add(k,A);n=safe_add(n,E)}return[b,d,k,n]}function md5_cmn(a,c,b,d,k,n){return safe_add(bit_rol(safe_add(safe_add(c,a),safe_add(d,n)),k),b)}function md5_ff(a,c,b,d,k,n,l){return md5_cmn(c&b|~c&d,a,c,k,n,l)}function md5_gg(a,c,b,d,k,n,l){return md5_cmn(c&d|b&~d,a,c,k,n,l)}function md5_hh(a,c,b,d,k,n,l){return md5_cmn(c^b^d,a,c,k,n,l)}function md5_ii(a,c,b,d,k,n,l){return md5_cmn(b^(c|~d),a,c,k,n,l)}
function safe_add(a,c){var b=(65535&a)+(65535&c);return(a>>16)+(c>>16)+(b>>16)<<16|65535&b}function bit_rol(a,c){return a<<c|a>>>32-c}cc.keywordNotStyle=["element","_childStyle","state"];
cc.Node=cc.Class.extend({_name:"",_lcid:0,_countChild:0,_render:null,_children:null,_parent:null,_style:null,_nodeType:"Node",ctor:function(a){this._initRender(a);a&&this.css(a)},_initRender:function(a){null==a&&(a={});cc.isEmpty(a.element)&&(a.element=cc.getHtml(this._html));if(!cc.isEmpty(a.element)){if(cc.isString(a.element))try{var c=document.createElement("div");c.textContent=a.element.trim();var b=c.firstChild;if(b&&1==b.nodeType){this._render=b;this._render.setAttribute("_nt",this.getType());
return}}catch(d){cc.log("error create element from  html :"+a.element+":"+this._idLocal+":"+this.getType())}if(a.element instanceof HTMLElement){this._render=a.element;this._render.setAttribute("_nt",this.getType());return}}this._render=document.createElement("div");this._render.setAttribute("_nt",this.getType())},appendTo:function(a){a instanceof HTMLElement&&a.appendChild(this._render)},addChild:function(a){a._nodeType&&this._render&&a._render instanceof HTMLElement&&(this._render.appendChild(a._render),
this._children=this._children||{},a._lcid=this._countChild++,this._children[a._lcid]=a,a._parent=this)},removeChild:function(a,c){a._parent&&a._parent._render&&a._parent._render.removeChild(a._render);delete this._children[a._idNode];c&&a.release&&a.release()},removeAllChild:function(){for(var a in this._children)this.removeChild(this._children[a])},children:function(){var a=[],c;for(c in this._children)a.push(this._children);return a},getParent:function(){return this._parent},getRender:function(){return this._render},
getChildrenByName:function(a){if(cc.isEmpty(a))return null;for(var c in this._children)if(this._children[c].name==a)return this._children[c]},getChildByLcId:function(a){return!cc.isNumber(a)||0>Number(a)?null:this._children[a]?this._children[a]:null},toObject:function(){},fromObject:function(a){this._countChild=a.countChild?a.countChild:this._countChild},getType:function(){return this._nodeType},_release:function(){this.removeAllChild();this._render=null;this.removeAllCEventListener()},cssChild:function(a){if(this._render)for(var c in a){var b=
this._render.getChildrenByName(c);if(b)for(var d=0;d<b.length;d++)this.cssDom(b[d],a[c])}},css:function(a,c){if(!this._render||!this._render.style)return!1;this._style=this._style||{};var b=!0;if(cc.isString(a)){if(!c)return this._render.style[a];0>cc.keywordNotStyle.indexOf(a)&&(a=this._replaceCssProperties(a),this._render.style[a]=c,this._render.style[a]==c?this._style[a]=c:b=!1)}else{a=this._replaceCssProperties(a);for(var d in a)0>cc.keywordNotStyle.indexOf(d)?(this._render.style[d]=a[d],this._render.style[d]==
a[d]?this._style[d]=a[d]:b=!1):"_childStyle"==d&&this.cssChild(a[d])}""!=this._render.style.display&&"none"!=this._render.style.display&&(this._render.style.cdisplay=this._render.style.display);if(this._style.scaleX||this._style.scaleY||this._style.rotation)d="",this._style.rotation&&(d+="rotate("+this._style.rotation+"deg) "),this._style.scaleX&&(d+="scaleX("+this._style.scaleX+") "),this._style.scaleY&&(d+="scaleY("+this._style.scaleY+") "),this._render.style.transform=d;return b},cssDom:function(a,
c,b){if(cc.isString(c))c=this._replaceCssProperties(c),a.style[c]=b;else{c=this._replaceCssProperties(c);for(var d in c)a.style[d]=c[d]}},_replaceCssProperties:function(a){cc.isObject(a)&&(void 0!=a.x&&(a.left=a.x),void 0!=a.y&&(a.top=a.y),void 0!=a.rotate&&(a.rotation=a.rotate),delete a.x,delete a.y);if(cc.isString(a)){if("x"==a)return"left";if("y"==a)return"top";if("rotate"==a)return"ratation"}return a},_renderStyle:function(){return this._render&&this._render.style?this._render.style:null},setWidth:function(a){return this._renderStyle()?
cc.isString(a)?this.css("width",a):!cc.isNumber(a)||0>Number(a)?!1:this.css("width",a+"px"):!1},getWidth:function(){return this._renderStyle()?parseInt(this._render.style.width):0},setHeight:function(a){return this._renderStyle()?cc.isString(a)?this.css("height",a):!cc.isNumber(a)||0>Number(a)?!1:this.css("height",a+"px"):!1},getHeight:function(){return this._renderStyle()?parseInt(this._render.style.height):0},setX:function(a){return this._renderStyle()&&cc.isNumber(a)?this.css("left",a+"px"):!1},
getX:function(){return this._renderStyle()?parseInt(this._render.style.left):0},setY:function(a){return this._renderStyle()&&cc.isNumber(a)?this.css("top",a+"px"):!1},getY:function(){return this._renderStyle()?parseInt(this._render.style.top):0},getClientBoudingBox:function(){return this._render&&this._render.getClientBoudingBox?this._render.getClientBoudingBox():null},setVisible:function(a){this._renderStyle()&&(this._render.style.display=a?cc.isUndefined(this._render.style.cdisplay)?"":this._render.style.cdisplay:
"none")},getVisible:function(){return this._renderStyle()?"none"==this._render.style.display?!0:!1:!1},setColor:function(a){return this._renderStyle()?this.css("color",a):!1},getColor:function(){return this._renderStyle()?this._render.style.color.toString():""},setOpacity:function(a){return this._renderStyle()?this.css("opacity",a):!1},getOpacity:function(){return this._renderStyle()&&cc.isNumber(this._render.style.opacity)?this._render.style.opacity:1},setRotate:function(a){return!this._renderStyle()||
!cc.isNumber(a)||0>Number(a)?!1:this.css("rotation",a)},getRotate:function(){return this._renderStyle()&&this._style.rotation?this._style.rotation:0},setScaleX:function(a){return this._renderStyle()&&cc.isNumber(a)?this.css("scaleX",a):!1},getScaleX:function(){return this._renderStyle()&&this._style.scaleX?this._style.scaleX:1},setScaleY:function(a){return this._renderStyle()&&cc.isNumber(a)?this.css("scaleY",a):!1},getScaleY:function(){return this._renderStyle()&&this._style.scaleY?this._style.scaleY:
1},setScale:function(a,c){this.setScaleX(a);this.setScaleY(c)},setButtonMode:function(a){if(!this._renderStyle())return!1;a?this.css("cursor","pointer"):this.css("cursor","default")},anim:function(a,c,b,d){cc.isObject(a)||cc.isArray(a)?this.animFromTo(null,a,c,b,d):cc.isString(a)&&this._render&&(a=cc.animePattern.getFromTo(a,this))&&(c&&(a.to.duration=c),this.animFromTo(a.from,a.to,c,b,d))},animFromTo:function(a,c,b,d,k){if(this._render&&c&&(cc.isArray(c)||cc.isObject(c))){d&&"true"==d.toString().trim()||
(d=!1);null==k&&(k="normal");try{this.stopAnim();this.timeline=anime.timeline({targets:this._render,loop:d,duration:Number(b),direction:k});a&&cc.isObject(a)&&(a=this._replaceCssProperties(a),this.timeline._from=a,this.css(a));if(cc.isArray(c))for(a=0;a<c.length;a++)c[a]=this._replaceCssProperties(c[a]),this.timeline.add(c[a]);else cc.isObject(c)&&(c=this._replaceCssProperties(c),this.timeline.add(c));this.timeline._animto=c}catch(n){cc.log("runAnim error "+n.message)}}},stopAnimToEnd:function(){this.timeline&&
this.timeline.pause();anime.remove(this._render);for(var a=0;a<this.timeline._animto.length;a++){var c=this.timeline._animto[a];delete c.targets;delete c.easing;delete c.duration;delete c.delay;delete c.endDelay;delete c.round;this.css(c)}delete this.timeline._from;delete this.timeline._timelines},stopAnim:function(){this.timeline&&(this.timeline.pause(),anime.remove(this._render),delete this.timeline._from,delete this.timeline._timelines)},addTouchStart:function(a){this.addDomTouchStart(this._render,
a)},removeTouchStart:function(){this.removeDomTouchStart(this._render)},addDomTouchStart:function(a,c){var b=this;a.touchStartEnabled=!0;a.addEventListener("mousedown",function(d){b._onDomDown(d,c)});a.addEventListener("touchstart",function(d){b._onDomDown(d,c);d.preventDefault()})},_onDomDown:function(a,c){if(a.currentTarget.touchStartEnabled){var b=a.touches&&0<a.touches.length?a.touches[0]:a,d=a.currentTarget;b.target=d==this._render?this:d;b.time=(new Date).getTime();cc.removeDomAttr(d,"move_time move_pageX move_pageY move_clientX move_clientY end_time".split(" "));
d.setAttribute("start_time",b.time);d.setAttribute("start_pageX",b.pageX);d.setAttribute("start_pageY",b.pageY);d.setAttribute("start_clientX",b.clientX);d.setAttribute("start_clientY",b.clientY);_windowUp();d.dragEnabled&&(cc.dragDom=d,d.setAttribute("start_left",parseInt(d.style.left)),d.setAttribute("start_top",parseInt(d.style.top)),window.addEventListener("mousemove",_windowMove),window.addEventListener("touchmove",_windowMove),window.addEventListener("mouseup",_windowUp),window.addEventListener("touchend",
_windowUp));c&&c(b)}},removeDomTouchStart:function(a){a.dragEnabled||(a.touchStartEnabled=!1)},addTouchMove:function(a){this.addDomTouchMove(this._render,a)},removeTouchMove:function(){this.removeDomTouchMove(this._render)},addDomTouchMove:function(a,c){var b=this;a.touchMoveEnabled=!0;a.addEventListener("mousemove",function(d){b._onDomMove(d,c)});a.addEventListener("touchmove",function(d){b._onDomMove(d,c);d.preventDefault()})},_onDomMove:function(a,c){if(a.currentTarget.touchMoveEnabled){var b=
a.touches&&0<a.touches.length?a.touches[0]:a,d=a.currentTarget;b.target=d==this._render?this:d;b.time=(new Date).getTime();d.setAttribute("move_time",b.time);d.setAttribute("move_pageX",b.pageX);d.setAttribute("move_pageY",b.pageY);d.setAttribute("move_clientX",b.clientX);d.setAttribute("move_clientY",b.clientY);c&&c(b)}},removeDomTouchMove:function(a){a.touchMoveEnabled=!1},addTouchOut:function(a){this.addDomTouchOut(this._render,a)},removeTouchOut:function(){this.removeDomTouchOut(this._render)},
addDomTouchOut:function(a,c){var b=this;a.touchOutEnabled=!0;a.addEventListener("mouseout",function(d){b._onDomOut(d,c)})},_onDomOut:function(a,c){if(a.target.touchOutEnabled){var b=a.touches&&0<a.touches.length?a.touches[0]:a,d=a.currentTarget;b.target=d==this._render?this:d;b.time=(new Date).getTime();c&&c(b)}},removeDomTouchOut:function(a){a.touchOutEnabled=!1},addTouchEnd:function(a){this.addDomTouchEnd(this._render,a)},removeTouchEnd:function(){this.removeDomTouchEnd(this._render)},addDomTouchEnd:function(a,
c){var b=this;a.touchEndEnabled=!0;a.addEventListener("mouseup",function(d){b._onDomEnd(d,c)});a.addEventListener("touchend",function(d){b._onDomEnd(d,c);d.preventDefault()})},_onDomEnd:function(a,c){if(a.currentTarget.touchEndEnabled){var b=a.touches&&0<a.touches.length?a.touches[0]:a,d=a.currentTarget;b.target=d==this._render?this:d;b.time=(new Date).getTime();d.setAttribute("end_time",b.time);c&&c(b);this._onDomTap(d);cc.removeDomAttr(d,"move_time move_pageX move_pageY move_clientX move_clientY end_time".split(" "));
cc.removeDomAttr(d,["start_time","start_pageX","start_pageY","start_clientX","start_clientY"])}},removeDomTouchEnd:function(a){a.touchEndEnabled=!1},addTouch:function(a){this.addTouchTap(a)},removeTouch:function(){this.removeTouchTap()},addDomTouch:function(a,c){this.addDomTouchTap(a,c)},addTouchTap:function(a){this.addDomTouchTap(this._render,a)},removeTouchTap:function(){this.removeDomTouchTap(this._render)},addDomTouchTap:function(a,c){a.touchStartEnabled||this.addDomTouchStart(a);a.touchEndEnabled||
this.addDomTouchEnd(a);a.touchTapEnabled=!0;a.callbacksTap=a.callbacksTap||[];c&&a.callbacksTap.push(c)},_onDomTap:function(a){a.getAttribute("move_pageX")||a.setAttribute("move_pageX",a.getAttribute("start_pageX"));a.getAttribute("move_pageY")||a.setAttribute("move_pageY",a.getAttribute("start_pageY"));if(150>cc.getAttrToNumber(a,"end_time")-cc.getAttrToNumber(a,"start_time")&&10>Math.abs(cc.getAttrToNumber(a,"start_pageX")-cc.getAttrToNumber(a,"move_pageX"))&&10>Math.abs(cc.getAttrToNumber(a,"start_pageY")-
cc.getAttrToNumber(a,"move_pageY"))){if(a.getAttribute("tap_time")&&200>(new Date).getTime()-cc.getAttrToNumber(a,"tap_time")){if(a.callbacksDoubleTap)for(var c=0;c<a.callbacksDoubleTap.length;c++)a.callbacksDoubleTap[c].call(null,{target:a==this._render?this._render:a})}else if(a.callbacksTap)for(c=0;c<a.callbacksTap.length;c++)a.callbacksTap[c].call(null,{target:a==this._render?this._render:a});a.setAttribute("tap_time",(new Date).getTime())}},removeDomTouchTap:function(a){a.callbacksTap&&(a.touchTapEnabled=
!1,a.callbacksTap=null,delete a.callbacksTap)},addTouchDouble:function(a){this.addDomTouchDoubleTap(this._render,a)},addTouchDoubleTap:function(a){this.addDomTouchDoubleTap(this._render,a)},removeTouchDoubleTap:function(){this.removeDomTouchDoubleTap(this._render)},addDomTouchDoubleTap:function(a,c){a.touchTapEnabled||this.addDomTouchTap(a);a.touchDoubleTapEnable=!0;a.callbacksDoubleTap=a.callbacksDoubleTap||[];c&&a.callbacksDoubleTap.push(c)},removeDomTouchDoubleTap:function(a){a.callbacksDoubleTap&&
(a.touchDoubleTapEnable=!1,a.callbacksDoubleTap=null,delete a.callbacksDoubleTap)},_dragEnabled:!1,setDragEnabled:function(a){this._render&&(this.setDragEnabledDom(this._render,a),this._dragEnabled=a)},getDragEnabled:function(){return this._dragEnabled},setDragEnabledDom:function(a,c){c&&!a.touchStartEnabled&&this.addDomTouchStart(a);a.dragEnabled=!!c},findDom:function(a){var c=this,b=null;if(!a)return null;a instanceof HTMLElement?b=a:cc.isString(a)&&(b=this._render.querySelector(a));b._ccinit||
(b._ccinit=!0,b.css=function(d,k){if(cc.isString(d))b.style[d]=k;else if(cc.isObject(d))for(var n in d)b.style[n]=d[n]},b.getBoxGrid=function(d){return c.findDom(b.querySelector("[grid='"+d+"']"))},b.addTouch=function(d){c.addDomTouchTap(b,d)},b.removeTouch=function(){c.removeDomTouchTap(b)},b.addTouchStart=function(d){c.addDomTouchStart(b,d)},b.removeTouchStart=function(){c.removeDomTouchStart(b)},b.addTouchMove=function(d){c.addDomTouchMove(b,d)},b.removeTouchMove=function(){c.removeDomTouchMove(b)},
b.addTouchOut=function(d){c.addDomTouchOut(b,d)},b.removeTouchOut=function(){c.removeDomTouchOut(b)},b.addTouchEnd=function(d){c.addDomTouchEnd(b,d)},b.removeTouchEnd=function(){c.removeDomTouchEnd(b)},b.addTouchDouble=function(d){c.addDomTouchDoubleTap(b,d)},b.removeTouchDouble=function(){c.removeDomTouchDoubleTap(b)});return b},findAllDom:function(a){}});cc.Node.fromObject=function(a){return cc.Node().fromObject(a)};var _p=cc.Node.prototype;cc.defineGetterSetter(_p,"parent",_p.getParent,_p.getParent);
cc.defineGetterSetter(_p,"render",_p.getRender,_p.getRender);cc.defineGetterSetter(_p,"width",_p.getWidth,_p.setWidth);cc.defineGetterSetter(_p,"height",_p.getHeight,_p.setHeight);cc.defineGetterSetter(_p,"x",_p.getX,_p.setX);cc.defineGetterSetter(_p,"left",_p.getX,_p.setX);cc.defineGetterSetter(_p,"y",_p.getY,_p.setY);cc.defineGetterSetter(_p,"top",_p.getY,_p.setY);cc.defineGetterSetter(_p,"visible",_p.getVisible,_p.setVisible);cc.defineGetterSetter(_p,"opacity",_p.getOpacity,_p.setOpacity);
cc.defineGetterSetter(_p,"color",_p.getColor,_p.setColor);cc.defineGetterSetter(_p,"scale",_p.getScale,_p.getScale);cc.defineGetterSetter(_p,"scaleX",_p.getScaleX,_p.setScaleX);cc.defineGetterSetter(_p,"scaleY",_p.getScaleY,_p.setScaleY);cc.defineGetterSetter(_p,"rotate",_p.getRotate,_p.setRotate);cc.defineGetterSetter(_p,"buttonMode",_p.setButtonMode,_p.setButtonMode);cc.defineGetterSetter(_p,"anchorX",_p.getAnchorX,_p.setAnchorX);cc.defineGetterSetter(_p,"anchorY",_p.getAnchorY,_p.setAnchorY);
cc.defineGetterSetter(_p,"touchEnabled",_p.getTouchEnabled,_p.setTouchEnabled);cc.defineGetterSetter(_p,"dragEnabled",_p.getDragEnabled,_p.setDragEnabled);
function _windowMove(a){var c=a.touches&&0<a.touches.length?a.touches[0]:a;a=cc.dragDom;var b=c.pageX-cc.getAttrToNumber(a,"start_pageX");c=c.pageY-cc.getAttrToNumber(a,"start_pageY");a==this._render?(this.x=b+cc.getAttrToNumber(a,"start_left"),this.y=c+cc.getAttrToNumber(a,"start_top")):(a.style.left=b+cc.getAttrToNumber(a,"start_left")+"px",a.style.top=c+cc.getAttrToNumber(a,"start_top")+"px")}
function _windowUp(a){window.removeEventListener("mousemove",_windowMove);window.removeEventListener("touchmove",_windowMove);window.removeEventListener("mouseup",_windowUp);window.removeEventListener("touchend",_windowUp);cc.dragDom&&cc.dragDom.removeAttribute("start_left");cc.dragDom&&cc.dragDom.removeAttribute("start_top");cc.dragDom&&cc.removeDomAttr(cc.dragDom,["start_time","start_pageX","start_pageY","start_clientX","start_clientY"]);cc.dragDom=null}var aztExam=aztExam||{};
aztExam.MonitorStudent=function(){function a(b){return{prepairSession:function(){},startSession:function(){},stopSession:function(){}}}var c;return{getInstance:function(b){null==c&&(c=a(b));return c},releaseInst:function(){c=null},inst:function(){return this.getInstance()}}}();
aztExam.MonitorTeacher=function(){function a(b){return{prepairSession:function(){},startSession:function(){},stopSession:function(){}}}var c;return{getInstance:function(b){null==c&&(c=a(b));return c},releaseInst:function(){c=null},inst:function(){return this.getInstance()}}}();